# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true
# Mod properties
mod_version = 3.2.7
maven_group = io.github.skydynamic
mod_id = quickbakcupmulti_reforged
archives_name = QuickBakcupMulti-Reforged
enabled_platforms = fabric,neoforge
# Minecraft properties
minecraft_version = 26.2
minecraft_supported_versions = [26.2, 26.3)
# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.2
neoforge_version = 26.2.0.32-beta

incremental_storage_lib_version=1.3.0+build.26030517.05
